exclude: >
  (?x)^(
  docs|
  Makefile
  )

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: "v0.7.1"
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: debug-statements
      language: python
      language_version: python3.7
    - id: requirements-txt-fixer
    - id: name-tests-test
      args: ['--django']

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.7"
    hooks:
    - id: flake8
      name: flake8
      language: python
      files: \.py$
      language_version: python3.7
      exclude: tests
      additional_dependencies: ['flake8-builtins']

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: "v1.0.4"
    hooks:
    - id: python-bandit-vulnerability-check
      args: [--ignore-nosec, -f, screen, -iii, -lll, -x, ./tests, -x, ./.eggs, --recursive, .]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.1.0"
    hooks:
    - id: python-safety-dependencies-check
      language: python
      language_version: python3

  # seed isort to get consistent behaviour in CI
  - repo: https://github.com/asottile/seed-isort-config
    sha: "v1.9.0"
    hooks:
    - id: seed-isort-config
      language: python
      language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-isort
    sha: "v4.3.18"
    hooks:
    - id: isort
      language: python
      language_version: python3.7

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: "v0.28.0"
    hooks:
    - id: yapf
      args: [-i, -r]
      language: python
      language_version: python3.7
